//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrowing
    {
        public int Borrowing_ID { get; set; }
        public int Book_ID { get; set; }
        public int Borrower_ID { get; set; }
        public System.DateTime Date_Borrowed { get; set; }
        public System.DateTime Due_Date { get; set; }
        public Nullable<System.DateTime> Date_Returned { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Borrower Borrower { get; set; }
    }
}
